<logs><log LogGUID="26db9c95-3374-4e9a-b722-16bd0540bd41" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:22:48 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>ada06cd2-9229-4c03-90f7-6811fe9e7933</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>e1CT713yHdC7TK2sQH6Rwg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="3868d072-5919-4f06-a087-1fcf11ba60d9" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:22:48 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>9ea0666f-02f4-409f-90bc-d8ea47a6e3f7</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>CJUdJwkDUnskfLShbG01Og==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="3ebf0524-7ab4-4c58-b6b8-a5bf6253e0c7" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:22:48 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="f24c727e-439d-41ea-aaf6-3cd829db8c01" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:24:22 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="3b76f17a-b5b8-4531-a0df-79adc2ac79b2" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:25:00 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>1ec47076-02a7-445a-994b-759d88912ffd</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>kYZBf6Jzdnf6gTe1vGwpng==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - The wait operation timed out.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The wait operation timed out</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="a7c8f70e-85d3-4077-99b1-d2a2c91dd779" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:25:00 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>c3ff7069-8798-48ef-8f2e-49d0f1693bde</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>KPfHv43qmVt1mxhofyfGGw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - The wait operation timed out.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The wait operation timed out</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="924ce982-77e8-43b3-889c-f6a1bf335f0e" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:25:00 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="1c0efe9e-d347-40a5-88ea-60938490c24c" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:25:46 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>6550170a-01de-47e8-ac3f-b98888a23a43</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>zCwkt1tKc6Y16EEABoKsUA==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="e15b0d29-fa23-4e13-8a6b-ce5d38df8bf1" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:25:46 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>30974a00-939a-4873-a5e2-fe79d7e792fd</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>F+G0JkKvXp5qsnqxXi4Tdw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="5d10f7bd-c899-498f-81a5-589883a34f26" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:25:46 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="fa105ad1-e523-4c7c-8a66-a0b9d231f17b" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:26:34 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>b6675c8a-b0ee-4262-a826-d620ccfe28aa</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>dwdpcZEj1BFQZKDIWDtllg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="90b41ee8-33c6-4f9f-937a-3d159bf7003d" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:26:34 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>d98b59d7-2f1d-419c-abe7-90407d0acb9d</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>zud+GAIZv2eooDsN/lgyvA==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="38f74f37-fe0d-4315-b48c-1b928cc8fcd4" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:26:34 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="39c59641-80b4-4a0b-99fc-6cc90c59da80" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:28:36 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>baa04e2c-eeeb-41d9-8f1c-04238b41ab27</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>NsIjG8JaRBwlFVcCnpCxsQ==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="0d638958-4758-475b-ab66-593b6978836e" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:28:36 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>a345597a-19d1-468e-9d21-e328faf8dec4</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>Rp5mYYhEzfb4jxRYjMxdyA==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="393c1181-f8b2-4f24-a538-1f7ed796a709" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:28:36 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="6a800b53-924d-45c5-8cd3-f386c500ac30" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:28:50 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>20cf8f0d-1bae-4205-b018-bd206a7faa4e</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>xZ3+K3FM7LQX6UFtRPl6bg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="84c9655a-bb5a-4a4c-a662-faca0ed2dba9" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:28:50 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>c8cfb522-e476-4a79-9602-3aa97c0ccd45</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>tTixaFI26WwN3m5lfeTcdw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="7ce61f70-24a4-4606-87b0-5ded63355ef9" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:28:50 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="da8a9aed-7f97-4b80-bf4b-d35a7e00d1ff" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:36:19 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>0cddaecb-ff02-4bf2-b3a9-005f8ef673ac</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>6DKi9JuEY80FaMUQG4Kh3A==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="aac0f545-2aff-46a8-b7a5-30a0f7a3f430" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:36:19 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>50c342aa-5d4d-4cec-a598-308f55020c4c</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>Rnsku7qHaMGGCMD1cI7byg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="09a0d214-d63f-4283-a106-b2adc78de7b9" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:36:19 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="8869de9d-b252-45dc-8ef9-7e0a2c5d4be0" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:39:36 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>70fff131-72d2-4863-8fb3-c1ed38c5317c</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>a+y2zCd5t3Nhkgk97Afpaw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="6ae7d123-a515-4765-a2e8-38a257413505" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:39:36 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>a1638830-3443-4924-a150-f5bbf5d48d42</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>ELc4KXc4GWcyjMkUTpdY/Q==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="e2e062ee-d0af-4bdf-8af4-96179e8503af" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:39:36 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="d3d4b778-0616-44d5-a6e9-52531c194da5" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:40:24 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>a8d7b3db-adbe-4b18-837a-db6bb558de03</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>gTXd8JyHn6w47uINtSKjpA==</ExceptionHash><Message>Login failed for user 'IIS APPPOOL\tomtang'.</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="eb72a529-7f7a-4f04-8d6d-bfe3036e5993" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:40:24 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>e1c1d316-bc87-4e10-9c05-3a99164b9310</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>h78Qfr/5nFR55eV4F38f4Q==</ExceptionHash><Message>Login failed for user 'IIS APPPOOL\tomtang'.</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="4b018bd9-1ea6-454e-b0b8-33490a0cbf9d" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:40:24 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="cae1862f-a88a-4be5-9877-56a202ad6115" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:44:24 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>68010c75-a9d2-405f-be24-02de7993cf2c</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>qnpZU8RD5ar8z6mFBQp2jQ==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="e531a631-a682-4fa2-ac30-64a369bfd7b8" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:44:24 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>9302cea6-69c3-4483-bbe6-4ab0d6c916a1</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>Ns9ha/oUWNdyRCQBt8qnEw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="ad93f335-b9a5-4a30-860e-281b4cebe94b" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:44:24 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="f3a5da90-80e1-462b-8e27-bb8b1eff57d8" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:46:26 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>686f62e8-2e7b-4879-96e9-441968d89f93</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>EToNDkNR6GGtHIKkblHCSg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="e03a7a20-34f3-4e7f-a3b6-a68b19a35eed" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:46:26 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>840279fd-b51e-4636-bb33-7eed9919128f</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>qT0/Dlsk2lp+8j6acQY6xQ==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="7986bece-1b9f-4bb8-9fa9-7c6c735ce57d" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:46:26 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="a17d3acd-101e-4e51-a008-bd412ecd4c95" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:56:05 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>b0813ff7-70ef-4b8c-ade2-86ae3fd50289</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>yEvlWTNNtVNS3EmVg+VeJw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="abbe0921-b855-4205-b1a9-b36ab84cd93e" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:56:05 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>e7e94398-d071-40e8-8e48-10a49c2ff2f7</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>q70ZsOj3utdOZGkpCh/9mg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="29da28dc-7d7f-44bf-bb35-eff1d6438353" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/26/2015 11:56:05 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="723401bd-87ea-4b69-a249-46c7272c3462" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 9:34:50 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>eadacef6-416d-4e71-8ca7-7680caf571da</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>FpJqrAY9djhpX8pRaUQ/zA==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="ce74a6c4-aa6c-49f9-a72c-68eaf2d6d189" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 9:34:51 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>cdcaaeb1-45e8-4425-9090-ae93b47f43c6</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>X2bDOHpLx378IAwMOTvDDg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="8bac4d77-520d-4130-aa83-af32555dae0f" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 9:34:51 AM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="ceb7f571-faa9-473f-9bea-225957137745" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 9:59:38 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>fceda93e-e50a-4836-9e0b-8a8862c121cb</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>Fg1O+oXQQoDzy6TNZb8wNw==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="bdf3a54d-ebfe-4905-ae8d-efe4a5e699db" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 9:59:38 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>19f90c33-edd3-421b-bbad-239b3df0ae4b</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>AFgdOukD+LcJkNXMF3Upow==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="cf234ea3-52c9-4629-ab15-7a5e0954da1d" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 9:59:38 AM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="59ae942e-2691-44f1-8638-be5ee8c411ac" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 10:08:14 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>3b9f9e56-3c94-49cd-b403-d98fdb4bd11e</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>WgsaaqM7/Fw3Bq4B+r9ZJA==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Controllers.HostController.GetSettingsFromDatabase()</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="b80e4fda-b4ca-4a7d-86f0-6b7c28db87f4" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 10:08:14 AM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>94794351-2a84-4b3b-a038-7192d888b5a6</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>GRxX43y+tqVO+DLTJeHVCg==</ExceptionHash><Message>A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The message received was unexpected or badly formatted.)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Portals.PortalAliasController.&lt;GetPortalAliasesInternal&gt;b__11(CacheItemArgs c)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromDictionary(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage>The message received was unexpected or badly formatted</InnerMessage><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="9db29ca4-c716-4c8a-9a1c-9e4880bde0ce" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="2/28/2015 10:08:14 AM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="Tom-MSI" LogConfigID=""><LogProperties><LogProperty><PropertyName>Url Processing Exception</PropertyName><PropertyValue>Exception in Url Rewriting Process</PropertyValue></LogProperty><LogProperty><PropertyName>Http Status</PropertyName><PropertyValue>500 Internal Server Error</PropertyValue></LogProperty><LogProperty><PropertyName>Original Path</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Raw Url</PropertyName><PropertyValue>/</PropertyValue></LogProperty><LogProperty><PropertyName>Final Url</PropertyName><PropertyValue>null</PropertyValue></LogProperty><LogProperty><PropertyName>Rewrite Result</PropertyName><PropertyValue>[no rewrite]</PropertyValue></LogProperty><LogProperty><PropertyName>Redirect Location</PropertyName><PropertyValue>[no redirect]</PropertyValue></LogProperty><LogProperty><PropertyName>Action</PropertyName><PropertyValue>Continue</PropertyValue></LogProperty><LogProperty><PropertyName>Reason</PropertyName><PropertyValue>Exception</PropertyValue></LogProperty><LogProperty><PropertyName>Portal Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Tab Id</PropertyName><PropertyValue>-1</PropertyValue></LogProperty><LogProperty><PropertyName>Http Alias</PropertyName><PropertyValue>Null</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 1</PropertyName><PropertyValue>Exception: Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 2</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS): Stack Trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requ</PropertyValue></LogProperty><LogProperty><PropertyName>Debug Message 3</PropertyName><PropertyValue>Inner Ex : null</PropertyValue></LogProperty><LogProperty><PropertyName>Exception Type</PropertyName><PropertyValue>System.ArgumentNullException</PropertyValue></LogProperty><LogProperty><PropertyName>Message</PropertyName><PropertyValue>Value cannot be null.
Parameter name: source</PropertyValue></LogProperty><LogProperty><PropertyName>Stack Trace</PropertyName><PropertyValue>(TRUNCATED TO 500 CHARS):    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasLookupInternal(String alias)
   at DotNetNuke.Entities.Portals.PortalAliasController.GetPortalAliasInternal(String httpAlias)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequestForWebServer(String requestedPath)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.IgnoreRequest(UrlAction result, String requestedPath, St</PropertyValue></LogProperty></LogProperties></log></logs>
